name: "Terraform CI/CD"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted 
    env:
      # secrets stored securely in GitHub → used as env vars
      PROXMOX_NODE: mercury.proxmox.home.arpa
      PROXMOX_API_USER: root@pam
      PROXMOX_API_TOKEN_ID: terraform-token
      PROXMOX_API_TOKEN_SECRET: ${{ secrets.PROXMOX_API_TOKEN_SECRET }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.4 

      - name: Terraform Init
        run: terraform init \
          -backend-config="bucket=..." \
          -backend-config="key=state/pve-talos-cluster.tfstate" \
          # other backend-config if needed

      - name: Terraform Fmt & Validate
        run: terraform fmt -check && terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Optionally: create a human review / approval step here for production
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve ./tfplan

      - name: VM IP Output
        run: python3 scripts/get_vm_ips.py
